// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnG7sMydui-EbXgjzWTFKepk2AiCfZZqE',
    appId: '1:241528104479:web:1210c173e2434e4ab6572a',
    messagingSenderId: '241528104479',
    projectId: 'moneyexpenx',
    authDomain: 'moneyexpenx.firebaseapp.com',
    storageBucket: 'moneyexpenx.firebasestorage.app',
    measurementId: 'G-TEC9XPFJN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBraogumS5jGsd0t1O93o6KoBkNCTUB8f8',
    appId: '1:241528104479:android:da5a73d26658aa01b6572a',
    messagingSenderId: '241528104479',
    projectId: 'moneyexpenx',
    storageBucket: 'moneyexpenx.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVHbkA6qW2eGS4sn5nYymtxsGx8lMTuE',
    appId: '1:241528104479:ios:485fb81abf0d7ddab6572a',
    messagingSenderId: '241528104479',
    projectId: 'moneyexpenx',
    storageBucket: 'moneyexpenx.firebasestorage.app',
    iosBundleId: 'com.moneyexpenx.moneyexpenx',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMVHbkA6qW2eGS4sn5nYymtxsGx8lMTuE',
    appId: '1:241528104479:ios:485fb81abf0d7ddab6572a',
    messagingSenderId: '241528104479',
    projectId: 'moneyexpenx',
    storageBucket: 'moneyexpenx.firebasestorage.app',
    iosBundleId: 'com.moneyexpenx.moneyexpenx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnG7sMydui-EbXgjzWTFKepk2AiCfZZqE',
    appId: '1:241528104479:web:c6627cbc710fa0a6b6572a',
    messagingSenderId: '241528104479',
    projectId: 'moneyexpenx',
    authDomain: 'moneyexpenx.firebaseapp.com',
    storageBucket: 'moneyexpenx.firebasestorage.app',
    measurementId: 'G-KZ1TER1JSM',
  );
}
